from tatuia import TatuIA 
from messageutils import MessageUtils # nossa classe de pré-processamento
from sklearn.metrics import classification_report

#import seaborn as sn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



def main():
    # database = {
    #     "intents": [
    #             {
    #                 "tag": "welcome",
    #                 "patterns": ['oi','ola','boa tarde','bom dia','boa noite','saudações','fala','eae','salve'],
    #                 "responses": ["Olá, serei seu assistente virtual, em que posso te ajudar?","Salve, qual foi ?", "Manda pro pai, Lança a braba", "No que posso te ajudar ?"],
    #                 "context": [""]
    #             },
    #             {
    #                 "tag": "my_classes",
    #                 "patterns": ['materias', 'materia', 'sala', 'disciplina','professor','local','turma','turmas','professores','disciplinas','salas','aula','aulas','grade','horario','classe','classes','cadeira','cadeiras','sala de aula','local de estudo','disciplinas matriculadas'],
    #                 "responses": ["Entendi, você deseja saber suas salas","Você deseja saber suas salas ?", "Ah, você quer saber qual sala ? ", "Suas Aulas ?"],
    #                 "context": [""]
    #             },
    #             {
    #                 "tag": "bus_info",
    #                 "patterns": ['fretado','fretados','onibus','busao','lotação','coletivo','circular','transporte','carro','veículo'],
    #                 "responses": ["Fretados","Horarios Fretado"], #provisório
    #                 "context": [""]
    #             },
    #             {
    #                 "tag": "anything_else",
    #                 "patterns": [],
    #                 "responses": ["Desculpa, não entendi o que você falou, tente novamente!","Não compreendi a sua solicitação, talvez eu possa te ajudar"],
    #                 "context": [""]
    #             }
    #         ]
    #     }

    database = {
        "intents": [
                {
                    "tag": "welcome",
                    "patterns": ['oi','ola','boa tarde','bom dia','boa noite','saudações','fala','eae','salve','fala','fala meu bom','grande bot'],
                    "responses": ["Olá, serei seu assistente virtual, em que posso te ajudar?","Salve, qual foi ?", "Manda pro pai, Lança a braba", "No que posso te ajudar ?"],
                    "context": [""]
                },
                {
                    "tag": "my_classes",
                    "patterns": ['informe a classes',
                        'qual minha aula',
                        'diga a  local',
                        'diga a  aulas',
                        'minhas local',
                        ' classes',
                        'diga a  salas',
                        'quero minhas professor',
                        ' classe',
                        ' turmas',
                        'quero minhas materias',
                        'qual é horario',
                        ' horario',
                        'informe a horario',
                        ' classes',
                        ' sala',
                        'quais as minhas professores',
                        ' disciplinas',
                        'quero saber as materias',
                        'quero minhas local',
                        'qual é professores',
                        'qual é professor',
                        'quero minhas professor',
                        'qual minha classes',
                        'diga a  professores',
                        'me fale as professores',
                        ' turmas',
                        ' turmas',
                        'diga a  classes',
                        'diz a materias',
                        'quero saber as classes',
                        'qual é sala',
                        'informe a classe',
                        'qual minha grade',
                        'me fale as professor',
                        'diga a  turma',
                        ' aulas',
                        ' professores',
                        'quero saber as materias',
                        'diz a grade',
                        ' materia',
                        'qual é disciplinas',
                        ' professores',
                        'qual minha classe',
                        'diga a  salas',
                        'quero saber as materias',
                        'diga a  salas',
                        'quero minhas salas',
                        'quero minhas aula',
                        'quero minhas horario',
                        'quero saber as professor',
                        'quero saber as professor',
                        ' turma',
                        'me fale as aula',
                        'qual minha turmas',
                        ' grade',
                        'qual é grade',
                        'me fale as horario',
                        ' local',
                        'diz a sala',
                        'me fale as classes',
                        'minhas salas',
                        'quero minhas horario',
                        'informe a salas',
                        'qual minha professor',
                        'informe a professores',
                        'diz a disciplinas',
                        'diga a  professor',
                        'me fale as horario',
                        'qual é disciplina',
                        'minhas grade',
                        ' aulas',
                        'quais as minhas sala',
                        ' horario',
                        'quais as minhas disciplinas',
                        'diz a disciplina',
                        'diz a classes',
                        'me fale as turma',
                        'qual minha horario',
                        'quais as minhas turmas',
                        'quais as minhas local',
                        ' disciplina',
                        ' disciplinas',
                        'quero minhas materias',
                        'me fale as materia',
                        'informe a professores',
                        'quero saber as materia',
                        'quais as minhas professores',
                        ' aula',
                        'me fale as materias',
                        'me fale as aula',
                        ' professores',
                        'minhas materias',
                        'quais as minhas materia',
                        'quais as minhas disciplinas',
                        'diga a  professores',
                        ' aula',
                        'qual minha local',
                        'quero saber as disciplina',
                        ' aulas',
                        'diz a turma',
                        'diga a  materia',
                        'quais as minhas professores',
                        'quero minhas disciplinas',
                        'quais as minhas classe',
                        'qual minha classes',
                        ' classes',
                        ' horario',
                        'qual minha disciplina',
                        'informe a aulas',
                        'quais as minhas disciplinas',
                        ' aulas',
                        'qual minha turma',
                        'quero saber as aula',
                        'quero minhas materias',
                        'me fale as professores',
                        'qual é aula',
                        'qual minha salas',
                        'diz a grade',
                        ' salas',
                        ' disciplina',
                        'diz a classe',
                        'diz a materias',
                        'qual minha professor',
                        'qual é disciplina',
                        ' professores',
                        ' sala',
                        'diz a grade',
                        'quero saber as disciplina',
                        'diz a classes',
                        ' classe',
                        ' salas',
                        ' local',
                        'quero saber as sala',
                        'qual minha turmas',
                        'qual é disciplina',
                        'diz a aula',
                        'me fale as aulas',
                        'quero saber as aulas',
                        'qual minha materia',
                        'qual é disciplina',
                        'minhas grade',
                        ' disciplinas',
                        'quero minhas aulas',
                        'informe a materias',
                        'me fale as horario',
                        'quero saber as grade',
                        'informe a aula',
                        'diz a classe',
                        ' professor',
                        ' disciplinas',
                        ' local',
                        'informe a disciplina',
                        'quero minhas turmas',
                        'quero minhas classe',
                        'quais as minhas disciplina',
                        'qual é grade',
                        ' turmas',
                        'me fale as disciplinas',
                        'me fale as professores',
                        ' grade',
                        'qual é materia',
                        'diga a  classes',
                        'qual é classes',
                        'me fale as classes',
                        'quero minhas local',
                        'diga a  aula',
                        'qual é materia',
                        ' salas',
                        ' turma',
                        ' disciplina',
                        'quero minhas horario',
                        ' materias',
                        ' classe',
                        'quais as minhas local',
                        'diga a  grade',
                        'minhas local',
                        ' grade',
                        'informe a turmas',
                        'me fale as professor',
                        'diz a disciplina',
                        'quero minhas grade',
                        ' materias',
                        'quais as minhas disciplina',
                        'quero minhas materia',
                        ' disciplina',
                        'informe a materia',
                        ' professores',
                        'diga a  salas',
                        'quero minhas turmas',
                        ' sala',
                        ' grade',
                        'quais as minhas aula',
                        'quero minhas salas',
                        'diga a  aulas',
                        'diga a  aulas',
                        'me fale as disciplinas',
                        ' disciplina',
                        'quero minhas local',
                        ' disciplina'],
                    "responses": ["Entendi, você deseja saber suas salas","Você deseja saber suas salas ?", "Ah, você quer saber qual sala ? ", "Suas Aulas ?"],
                    "context": [""]
                },
                {
                    "tag": "bus_info",
                    "patterns": ['quando busao',
                                'quando busao',
                                ' onibus',
                                'quero saber lotação',
                                'quando sai onibus',
                                'vai sair fretados',
                                'qual fretados',
                                'quero saber fretado',
                                ' lotação',
                                ' onibus',
                                'qual onibus',
                                'quando busao',
                                'informe lotação',
                                'que hora lotação',
                                ' lotação',
                                'quando onibus',
                                ' lotação',
                                'informe fretado',
                                'quando fretado',
                                ' lotação',
                                ' fretados',
                                'qual fretados',
                                'qual onibus',
                                'quero que sai busao',
                                'que hora fretado',
                                ' fretados',
                                'quero saber fretados',
                                ' onibus',
                                ' fretados',
                                'informe lotação',
                                'quando sai lotação',
                                'que hora fretados',
                                'informe fretados',
                                ' lotação',
                                'quando onibus',
                                'que hora fretados',
                                'quando sai lotação',
                                ' fretados',
                                ' fretado',
                                'quando sai onibus',
                                'vai sair busao',
                                'quero que sai busao',
                                'quando busao',
                                ' onibus',
                                'que hora onibus',
                                'vai sair fretados',
                                'informe fretado',
                                ' lotação',
                                'que hora fretado',
                                'vai sair fretados'],
                    "responses": ["Fretados","Horarios Fretado"], #provisório
                    "context": [""]
                },
                {
                    "tag": "anything_else",
                    "patterns": [],
                    "responses": ["Desculpa, não entendi o que você falou, tente novamente!","Não compreendi a sua solicitação, talvez eu possa te ajudar"],
                    "context": [""]
                }
            ]
        }

    message_utils = MessageUtils()
    message_utils.process_training_data(database,None)


    tatu_zap = TatuIA("", message_utils=message_utils,lstm = True)
    tatu_zap.print_model()
    tatu_zap.eval_model()
    X = ['informe a turmas', 'quero saber as sala', 'quais as minhas aulas', ' classes', ' professor', ' local', 'quais as minhas disciplina', 'quero saber as professores', 'informe a disciplina', 'quero saber as grade', ' aulas', 'qual é aulas', 'qual minha classes', 'quais as minhas materias', 'diz a materia', 'quero minhas disciplinas', 'minhas classe', 'minhas disciplinas', 'qual é materias', 'informe a materia', 'Oi', 'Oi, bom dia', 'Oi, boa tarde', 'bom dia', 'boa tarde', 'boa noite', 'oi, boa noite', 'olá, boa noite', 'oiiiii', 'Olá', 'oiii, como vai?', 'opa, tudo bem?', 'quando sai onibus', ' lotação', 'qual busao', 'quero saber fretado', 'qual fretado', 'informe fretado', 'quero que sai fretado', 'informe lotação', 'vai sair busao', 'quero saber fretados', ' busao', 'quando onibus', 'que hora lotação', 'que hora fretado',"asdasdasdas","cachorro voador","esquilo de chapeu", "gato de botas"]
    Y = ['my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info','anything_else','anything_else','anything_else','anything_else']

    
    list_predict = [(tatu_zap.get_predict(i)) for i in X]
        

    y_true = pd.Series(Y, name='Row_True')
    y_pred = pd.Series(list_predict, name='Col_Pred')
    df_confusion = pd.crosstab(y_true, y_pred)
    #df_confusion = pd.crosstab(y_pred, y_true,margins = 'True')

    print(df_confusion)
    print(classification_report(Y, list_predict))

if __name__ == "__main__":
    main()