from tatuia import TatuIA 
from messageutils import MessageUtils # nossa classe de pré-processamento
from sklearn.metrics import classification_report

#import seaborn as sn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



def main():
    # database = {
    #     "intents": [
    #             {
    #                 "tag": "welcome",
    #                 "patterns": ['oi','ola','boa tarde','bom dia','boa noite','saudações','fala','eae','salve'],
    #                 "responses": ["Olá, serei seu assistente virtual, em que posso te ajudar?","Salve, qual foi ?", "Manda pro pai, Lança a braba", "No que posso te ajudar ?"],
    #                 "context": [""]
    #             },
    #             {
    #                 "tag": "my_classes",
    #                 "patterns": ['materias', 'materia', 'sala', 'disciplina','professor','local','turma','turmas','professores','disciplinas','salas','aula','aulas','grade','horario','classe','classes','cadeira','cadeiras','sala de aula','local de estudo','disciplinas matriculadas'],
    #                 "responses": ["Entendi, você deseja saber suas salas","Você deseja saber suas salas ?", "Ah, você quer saber qual sala ? ", "Suas Aulas ?"],
    #                 "context": [""]
    #             },
    #             {
    #                 "tag": "bus_info",
    #                 "patterns": ['fretado','fretados','onibus','busao','lotação','coletivo','circular','transporte','carro','veículo'],
    #                 "responses": ["Fretados","Horarios Fretado"], #provisório
    #                 "context": [""]
    #             },
    #             {
    #                 "tag": "anything_else",
    #                 "patterns": [],
    #                 "responses": ["Desculpa, não entendi o que você falou, tente novamente!","Não compreendi a sua solicitação, talvez eu possa te ajudar"],
    #                 "context": [""]
    #             }
    #         ]
    #     }

    database = {
        "intents": [
                {
                    "tag": "welcome",
                    "patterns": ['oi','ola','boa tarde','bom dia','boa noite','saudações','fala','eae','salve','fala','fala meu bom','grande bot'],
                    "responses": ["Olá, serei seu assistente virtual, em que posso te ajudar?","Salve, qual foi ?", "Manda pro pai, Lança a braba", "No que posso te ajudar ?"],
                    "context": [""]
                },
                {
                    "tag": "my_classes",
                    "patterns": ['quero minhas grade ',
  ' grade que devo ir',
  'quero minhas classes na terca',
  'diga a  turma ',
  ' disciplinas na quinta',
  'minhas salas na quinta',
  'diga a  disciplina ',
  ' horario na sexta',
  ' materia agora',
  'minhas professores ',
  'minhas salas na quinta',
  'quais as minhas disciplina que devo ir',
  'me fale as horario na segunda',
  'me fale as local na segunda',
  'quero minhas salas na terca',
  'diz a disciplinas ',
  ' aula de manha',
  'quais as minhas salas na quarta',
  'diga a  aula ',
  'diz a materias na sexta',
  'diga a  disciplina de tarde',
  'me fale as materia na quarta',
  'quero saber as classe na segunda',
  'quero saber as professores ',
  ' horario na terca',
  'quero saber as professor na quarta',
  'quais as minhas aulas na sexta',
  'minhas materia ',
  'diga a  local ',
  'qual minha grade agora',
  ' disciplinas de noite',
  'quais as minhas classes ',
  'quais as minhas materia na quarta',
  'qual minha classe de manha',
  'quero saber as materia agora',
  'diz a turma ',
  'quero saber as salas de manha',
  'qual é local na terca',
  'quero minhas turma que devo ir',
  'quero minhas horario na segunda',
  'quero minhas materia na segunda',
  'informe a aulas de noite',
  'diz a grade agora',
  ' disciplina na sexta',
  'minhas materias agora',
  'minhas aulas de noite',
  'informe a professores que devo ir',
  'quais as minhas disciplinas na quinta',
  'quero saber as materias na segunda',
  'qual é sala na sexta',
  ' turma na terca',
  'qual é materia na sexta',
  'diga a  professor agora',
  'me fale as horario na sexta',
  'informe a classes de manha',
  'diga a  aulas agora',
  'minhas turmas ',
  'diga a  materia na segunda',
  'quero saber as materias que devo ir',
  ' salas de tarde',
  'minhas turma na quarta',
  'quais as minhas grade de manha',
  ' disciplina ',
  'informe a sala agora',
  'qual minha classes de noite',
  'qual é disciplinas na sexta',
  'minhas professores na sexta',
  ' professores ',
  ' grade ',
  ' classes de noite',
  'qual é salas ',
  'qual minha classes na terca',
  'qual minha aulas na terca',
  ' sala de noite',
  'diga a  turmas na quinta',
  'diga a  local ',
  'qual é materias ',
  ' classes ',
  'qual é classes de tarde',
  'diz a salas que devo ir',
  'diga a  turma na terca',
  'qual minha aula ',
  'minhas materia na sexta',
  'diga a  salas de tarde',
  'diz a professores agora',
  'quero minhas grade ',
  'me fale as local que devo ir',
  'qual é sala de manha',
  'me fale as turma ',
  'informe a grade na quarta',
  ' sala na segunda',
  'diz a materias agora',
  'minhas materia na quarta',
  ' materias na segunda',
  'minhas disciplinas na segunda',
  'qual minha local de tarde',
  'quero saber as grade de noite',
  'informe a disciplinas ',
  'diga a  materias na segunda',
  'informe a grade que devo ir',
  'minhas disciplinas na segunda',
  'quero minhas materias agora',
  'quero minhas turmas na sexta',
  'me fale as professor na segunda',
  'quero minhas professores ',
  ' disciplina ',
  'minhas local ',
  'quais as minhas salas na quinta',
  ' disciplina na quarta',
  'diz a materia agora',
  'diga a  materias ',
  'quais as minhas materias ',
  'me fale as horario na quarta',
  'quais as minhas aula ',
  'qual é horario ',
  'qual é turma de tarde',
  'me fale as materia que devo ir',
  'quais as minhas local de manha',
  'qual minha materias na quarta',
  'quais as minhas turma na quarta',
  ' aula que devo ir',
  'minhas materias de tarde',
  'quero minhas materias na segunda',
  ' aula ',
  'qual é local de noite',
  'informe a materias na quinta',
  'informe a local ',
  ' classes na segunda',
  'me fale as professores de manha',
  'diga a  classe na quinta',
  'qual é classe ',
  'diga a  professores ',
  'qual é classe de noite',
  ' sala ',
  'quero saber as sala na terca',
  'quero minhas sala que devo ir',
  'qual é turmas na quinta',
  ' materias de noite',
  ' aula na terca',
  ' materias de manha',
  'informe a professores ',
  'qual é aulas de noite',
  'qual é materias agora',
  ' local de tarde',
  ' horario de tarde',
  'diga a  materia que devo ir',
  'quero minhas materia ',
  'qual é disciplinas que devo ir',
  ' horario de tarde',
  'quero saber as classes na terca',
  'me fale as local de manha',
  'diz a professores ',
  'qual é sala na sexta',
  'quais as minhas classe ',
  'qual minha aulas ',
  'quero saber as turmas na quinta',
  ' local na sexta',
  'me fale as turma que devo ir',
  ' disciplinas na quarta',
  'qual é aulas na quarta',
  ' aulas na segunda',
  ' disciplinas de noite',
  ' turmas na quarta',
  'quero minhas classe na terca',
  'quero minhas sala na quarta',
  'me fale as disciplinas que devo ir',
  'informe a disciplina de noite',
  ' materias agora',
  'diga a  disciplinas de noite',
  'me fale as materias na quarta',
  ' sala na sexta',
  'quais as minhas materias de tarde',
  'qual é aula agora',
  'qual minha salas de noite',
  ' aula que devo ir',
  ' materia ',
  'quero saber as aula que devo ir',
  ' professores ',
  'qual é materias de manha',
  'diga a  turma de manha',
  'informe a professor agora',
  'quero saber as horario agora',
  'quero saber as aula na segunda',
  'quais as minhas horario de tarde',
  'informe a disciplina de tarde',
  ' materias de tarde',
  'qual minha materias na quarta',
  'qual é turmas agora',
  'quero minhas aulas na quinta',
  'qual é materias ',
  ' horario na segunda',
  'diga a  turmas de noite',
  'qual é turmas na terca',
  'quero saber as disciplinas de tarde',
  ' disciplinas na quinta',
  'minhas turmas de tarde',
  'qual é professores ',
  'quero minhas materias ',
  ' classes de noite',
  'diga a  salas de manha'],
                    "responses": ["Entendi, você deseja saber suas salas","Você deseja saber suas salas ?", "Ah, você quer saber qual sala ? ", "Suas Aulas ?"],
                    "context": [""]
                },
                {
                    "tag": "bus_info",
                    "patterns": ['quando busao',
                                'quando busao',
                                ' onibus',
                                'quero saber lotação',
                                'quando sai onibus',
                                'vai sair fretados',
                                'qual fretados',
                                'quero saber fretado',
                                ' lotação',
                                ' onibus',
                                'qual onibus',
                                'quando busao',
                                'informe lotação',
                                'que hora lotação',
                                ' lotação',
                                'quando onibus',
                                ' lotação',
                                'informe fretado',
                                'quando fretado',
                                ' lotação',
                                ' fretados',
                                'qual fretados',
                                'qual onibus',
                                'quero que sai busao',
                                'que hora fretado',
                                ' fretados',
                                'quero saber fretados',
                                ' onibus',
                                ' fretados',
                                'informe lotação',
                                'quando sai lotação',
                                'que hora fretados',
                                'informe fretados',
                                ' lotação',
                                'quando onibus',
                                'que hora fretados',
                                'quando sai lotação',
                                ' fretados',
                                ' fretado',
                                'quando sai onibus',
                                'vai sair busao',
                                'quero que sai busao',
                                'quando busao',
                                ' onibus',
                                'que hora onibus',
                                'vai sair fretados',
                                'informe fretado',
                                ' lotação',
                                'que hora fretado',
                                'vai sair fretados'],
                    "responses": ["Fretados","Horarios Fretado"], #provisório
                    "context": [""]
                },
                # {
                #     "tag": "disc_info",
                #     "patterns": ['Gostaria de saber da ementa da disciplina','ementa da materia','quero saber da ementa','quero saber do plano de ensino','quais os requsitos da materia','qual a bibliografia da disciplina'],
                #     "responses": ['Informações da disciplina X','Para a disciplina Y, as informações são as seguintes'],
                #     "context": [""]
                # },
                {
                    "tag": "anything_else",
                    "patterns": [],
                    "responses": ["Desculpa, não entendi o que você falou, tente novamente!","Não compreendi a sua solicitação, talvez eu possa te ajudar"],
                    "context": [""]
                }
            ]
        }

    message_utils = MessageUtils()
    message_utils.process_training_data(database,None)


    tatu_zap = TatuIA("", message_utils=message_utils,lstm = False)
    tatu_zap.print_model()
    tatu_zap.eval_model()
    X = ['informe a turmas', 'quero saber as sala', 'quais as minhas aulas', ' classes', ' professor', ' local', 'quais as minhas disciplina', 'quero saber as professores', 'informe a disciplina', 'quero saber as grade', ' aulas', 'qual é aulas', 'qual minha classes', 'quais as minhas materias', 'diz a materia', 'quero minhas disciplinas', 'minhas classe', 'minhas disciplinas', 'qual é materias', 'informe a materia', 'Oi', 'Oi, bom dia', 'Oi, boa tarde', 'bom dia', 'boa tarde', 'boa noite', 'oi, boa noite', 'olá, boa noite', 'oiiiii', 'Olá', 'oiii, como vai?', 'opa, tudo bem?', 'quando sai onibus', ' lotação', 'qual busao', 'quero saber fretado', 'qual fretado', 'informe fretado', 'quero que sai fretado', 'informe lotação', 'vai sair busao', 'quero saber fretados', ' busao', 'quando onibus', 'que hora lotação', 'que hora fretado',"asdasdasdas","cachorro voador","esquilo de chapeu", "gato de botas"]
    Y = ['my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'my_classes', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'welcome', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info', 'bus_info','anything_else','anything_else','anything_else','anything_else']

    
    list_predict = [(tatu_zap.get_predict(i)) for i in X]
        

    y_true = pd.Series(Y, name='Row_True')
    y_pred = pd.Series(list_predict, name='Col_Pred')
    df_confusion = pd.crosstab(y_true, y_pred)
    #df_confusion = pd.crosstab(y_pred, y_true,margins = 'True')

    print(df_confusion)
    print(classification_report(Y, list_predict))

if __name__ == "__main__":
    main()